#!/usr/bin/env bash
# configure — guided setup wizard. Prompts for config, validates it, writes .env,
# runs preflight, and offers to bootstrap. Dependency-free (plain prompts).
# Re-runnable: pre-fills defaults from an existing .env.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV="$ROOT/.env"
cd "$ROOT"

# Load existing .env as defaults if present.
[ -f "$ENV" ] && { set -a; . "$ENV"; set +a; }

bold(){ printf '\033[1m%s\033[0m\n' "$1"; }
ask(){ # ask <var> <prompt> <default> ; reads into global $var
  local var="$1" prompt="$2" def="${3:-}" cur="${!1:-}" val
  def="${cur:-$def}"
  if [ -n "$def" ]; then read -r -p "  $prompt [$def]: " val; else read -r -p "  $prompt: " val; fi
  printf -v "$var" '%s' "${val:-$def}"
}
asksecret(){ local var="$1" prompt="$2" cur="${!1:-}" val
  read -r -s -p "  $prompt$([ -n "$cur" ] && echo ' [keep existing]'): " val; echo
  printf -v "$var" '%s' "${val:-$cur}"
}

bold "AgentV setup wizard"
echo "Answer the prompts (Enter accepts the [default]). Nothing is sent anywhere; it just writes .env."
echo

bold "1) Control-plane database (MySQL 8)"
ask MYSQL_HOST "MySQL host" "${MYSQL_HOST:-127.0.0.1}"
ask MYSQL_USER "MySQL user" "${MYSQL_USER:-root}"
asksecret MYSQL_PASSWORD "MySQL password"
ask MYSQL_DATABASE "Control-plane schema name" "${MYSQL_DATABASE:-agentv}"

echo "  testing connection..."
if mysql -h "$MYSQL_HOST" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "SELECT 1" >/dev/null 2>&1; then
  echo "  ✓ connected"
else
  echo "  ✗ could not connect — you can continue, but fix creds before bootstrap."
fi

bold "2) Control-plane API + dashboard"
ask SERVER_PORT "API port" "${SERVER_PORT:-8100}"
ask DASHBOARD_APP_PORT "Dashboard app port" "${DASHBOARD_APP_PORT:-$((SERVER_PORT + 1))}"
ask DASHBOARD_DOMAIN "Public dashboard domain (blank = local-only)" "${DASHBOARD_DOMAIN:-}"
if [ -n "${JWT_SECRET:-}" ]; then echo "  JWT_SECRET: keeping existing"; else
  JWT_SECRET="$(openssl rand -hex 48 2>/dev/null || head -c48 /dev/urandom | xxd -p | tr -d '\n')"
  echo "  JWT_SECRET: generated"
fi
if [ -n "$DASHBOARD_DOMAIN" ]; then CONTROL_PLANE_API="https://$DASHBOARD_DOMAIN"; else CONTROL_PLANE_API="http://localhost:$SERVER_PORT"; fi

bold "3) Fleet + GitHub"
echo "  The single starter agent is the coordinator — name it whatever you like (Norman, AgentV, …)."
ask FLEET_MANAGER_NAME "Fleet-manager display name" "${FLEET_MANAGER_NAME:-Fleet Manager}"
# Derive a slug from the name unless one was already set: lowercase, spaces→-, strip junk.
_def_slug="$(printf '%s' "$FLEET_MANAGER_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-' | sed 's/--*/-/g; s/^-//; s/-$//')"
ask FLEET_MANAGER_SLUG "Fleet-manager slug (dir/session/DB)" "${FLEET_MANAGER_SLUG:-${_def_slug:-fleet-manager}}"
ask GITHUB_ORG "GitHub org for repos (blank ok for now)" "${GITHUB_ORG:-}"
ask APP_DOMAIN_BASE "Wildcard base for apps the fleet builds (blank ok)" "${APP_DOMAIN_BASE:-}"

bold "4) Email relay (digests/alerts — cloud IPs are blocklisted)"
ask MAIL_PROVIDER "Provider (brevo|sendgrid|ses|smtp|none)" "${MAIL_PROVIDER:-none}"
if [ "$MAIL_PROVIDER" != "none" ]; then
  asksecret MAIL_API_KEY "Relay API key"
  ask MAIL_FROM "From address" "${MAIL_FROM:-}"
  ask ADMIN_NOTIFY_TO "Admin recipient (you)" "${ADMIN_NOTIFY_TO:-}"
fi

bold "5) AI (optional at 2-agent stage)"
asksecret OPENROUTER_API_KEY "OpenRouter API key (image-gen; blank ok)"
ask DEFAULT_AGENT_MODEL "Default agent model" "${DEFAULT_AGENT_MODEL:-claude-sonnet-4-6}"

# --- write .env ---
umask 077
cat > "$ENV" <<EOF
# Generated by setup/configure.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
MYSQL_HOST=$MYSQL_HOST
MYSQL_USER=$MYSQL_USER
MYSQL_PASSWORD=$MYSQL_PASSWORD
MYSQL_DATABASE=$MYSQL_DATABASE
SERVER_PORT=$SERVER_PORT
NODE_ENV=production
JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=7d
CONTROL_PLANE_API=$CONTROL_PLANE_API
DASHBOARD_DOMAIN=$DASHBOARD_DOMAIN
DASHBOARD_APP_PORT=$DASHBOARD_APP_PORT
APP_DOMAIN_BASE=$APP_DOMAIN_BASE
PORT_RANGE_FROM=${PORT_RANGE_FROM:-8200}
PORT_RANGE_TO=${PORT_RANGE_TO:-8999}
FLEET_MANAGER_NAME=$FLEET_MANAGER_NAME
FLEET_MANAGER_SLUG=$FLEET_MANAGER_SLUG
GITHUB_ORG=$GITHUB_ORG
OPENROUTER_API_KEY=$OPENROUTER_API_KEY
DEFAULT_AGENT_MODEL=$DEFAULT_AGENT_MODEL
MAIL_PROVIDER=$MAIL_PROVIDER
MAIL_API_KEY=${MAIL_API_KEY:-}
MAIL_FROM=${MAIL_FROM:-}
ADMIN_NOTIFY_TO=${ADMIN_NOTIFY_TO:-}
EOF
echo; bold "✓ wrote $ENV (chmod 600)"

echo; bold "Before bootstrap, two one-time interactive logins (cannot be scripted):"
echo "  • gh auth login        (GitHub — for PRs)"
echo "  • claude               (Claude Code — log in once)"
[ -n "$DASHBOARD_DOMAIN" ] && echo "  • DNS: point $DASHBOARD_DOMAIN at this server so certbot can issue SSL."

echo; bold "Preflight check:"
bash setup/preflight.sh || true

echo
read -r -p "Run ./setup/bootstrap.sh now? [y/N]: " go
case "${go:-N}" in y|Y|yes) exec ./setup/bootstrap.sh ;; *) echo "Run ./setup/bootstrap.sh when ready." ;; esac
